brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path
from todos.views import todo_list, todo_list_detail, create_todo_list, todo_list_update



urlpatterns = [
    path('', todo_list, name='todo_list_list'),
    path('<int:id>/', todo_list_detail, name='todo_list_detail'),
    path('create/', create_todo_list, name='todo_list_create'),
    path('<int:id>/edit/', todo_list_update, name='todo_list_update'),
]

todos/models.py
from django.db import models


# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(
        null=True,
        blank=True,
    )
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        TodoList,
        on_delete=models.CASCADE,
        related_name='items',
        default=None,
    )

    def __str__(self):
        return self.task

todos/forms.py
from django import forms
from .models import TodoList

class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['name']

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from todos.models import TodoList, TodoItem
from .forms import TodoListForm

# Create your views here.
def todo_list(request):
    todo_lists = TodoList.objects.all()
    context = {
        "todos_list": todo_lists,
    }
    return render(request, "todos/list.html", context)

def todo_list_detail(request, id):
    todo_list_detail = TodoList.objects.get(id=id)
    context = {
        "todo_list_detail": todo_list_detail,
    }
    return render(request, "todos/details.html", context)

def create_todo_list(request):
    if request.method == "POST":
        form = TodoListForm(request.POST)
        if form.is_valid():
            task = form.save()
            return redirect("todo_list_detail", id=task.id)

    else:
        form = TodoListForm()

    context = {
        "form_key": form,
        }
    return render(request, "todos/create.html", context)

def todo_list_update(request, id):
    todo_list = TodoList.objects.get(id=id)
    if request.method == "POST":
        form = TodoListForm(request.POST, instance=todo_list)
        if form.is_valid():
            form = form.save()
            return redirect("todo_list_detail", todo_list.id)
    else:
        form = TodoListForm(instance=todo_list)

    context = {
        "form": form
    }

    return render(request, "todos/edit.html", context)

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form_key.as_p }}
                <button>Create</button>
              </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo details</title>
</head>
<body>
    <main>
        <div>
            <h1>{{todo_list_detail.name}}</h1>
            <h2>Tasks</h2>
            <p><a href="{% url "todo_list_update" todo_list_detail.id %}">update</a></p>
            <table>
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Due date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todos_item in todo_list_detail.items.all %}
                        <tr>
                            <!-- <td><a href="{% url "todo_list_detail" id=todos_item.id %}"></a></td> -->
                            <td><a>{{ todos_item.task }}</a></td>
                            <td>{{ todos_item.due_date }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>

</body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update</title>
</head>
<body>
    <main>
        <div>
            <h1>update list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>update</button>
              </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo List</title>
    </head>
    <body>
        <main>
            <div>
                <h1>My Lists</h1>
                <p><a href="{% url "todo_list_create" %}">create</a></p>

            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todos_list_detail in todos_list %}
                        <tr>
                            <td><a href="{% url "todo_list_detail" id=todos_list_detail.id %}"> {{ todos_list_detail.name }}</a></td>
                            <td>{{ todo_list.todoitem_set.count }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>